-- Staging (PostgreSQL / bank_dwh) — исходные таблицы банковской системы
-- Соответствуют apps.credit.models (src_*)

CREATE TABLE IF NOT EXISTS src_application_train (
    sk_id_curr BIGINT PRIMARY KEY,
    target SMALLINT,
    name_contract_type VARCHAR(64),
    code_gender VARCHAR(8),
    flag_own_car VARCHAR(8),
    flag_own_realty VARCHAR(8),
    cnt_children INTEGER,
    amt_income_total DOUBLE PRECISION,
    amt_credit DOUBLE PRECISION,
    amt_annuity DOUBLE PRECISION,
    amt_goods_price DOUBLE PRECISION,
    name_type_suite VARCHAR(128),
    name_income_type VARCHAR(64),
    name_education_type VARCHAR(64),
    name_family_status VARCHAR(64),
    name_housing_type VARCHAR(64),
    region_population_relative DOUBLE PRECISION,
    days_birth INTEGER,
    days_employed DOUBLE PRECISION,
    days_registration DOUBLE PRECISION,
    days_id_publish INTEGER,
    own_car_age DOUBLE PRECISION,
    flag_mobil INTEGER,
    flag_emp_phone INTEGER,
    flag_work_phone INTEGER,
    flag_cont_mobile INTEGER,
    flag_phone INTEGER,
    flag_email INTEGER,
    occupation_type VARCHAR(128),
    cnt_fam_members DOUBLE PRECISION,
    region_rating_client INTEGER,
    region_rating_client_w_city INTEGER,
    weekday_appr_process_start VARCHAR(16),
    hour_appr_process_start DOUBLE PRECISION,
    reg_region_not_live_region INTEGER,
    reg_region_not_work_region INTEGER,
    live_region_not_work_region INTEGER,
    reg_city_not_live_city INTEGER,
    reg_city_not_work_city INTEGER,
    live_city_not_work_city INTEGER,
    organization_type VARCHAR(128),
    ext_source_1 DOUBLE PRECISION,
    ext_source_2 DOUBLE PRECISION,
    ext_source_3 DOUBLE PRECISION,
    days_last_phone_change DOUBLE PRECISION,
    flag_document_2 INTEGER,
    flag_document_3 INTEGER,
    flag_document_4 INTEGER,
    flag_document_5 INTEGER,
    flag_document_6 INTEGER,
    flag_document_7 INTEGER,
    flag_document_8 INTEGER,
    flag_document_9 INTEGER,
    flag_document_10 INTEGER,
    flag_document_11 INTEGER,
    flag_document_12 INTEGER,
    flag_document_13 INTEGER,
    flag_document_14 INTEGER,
    flag_document_15 INTEGER,
    flag_document_16 INTEGER,
    flag_document_17 INTEGER,
    flag_document_18 INTEGER,
    flag_document_19 INTEGER,
    flag_document_20 INTEGER,
    flag_document_21 INTEGER,
    amt_req_credit_bureau_hour DOUBLE PRECISION,
    amt_req_credit_bureau_day DOUBLE PRECISION,
    amt_req_credit_bureau_week DOUBLE PRECISION,
    amt_req_credit_bureau_mon DOUBLE PRECISION,
    amt_req_credit_bureau_qrt DOUBLE PRECISION,
    amt_req_credit_bureau_year DOUBLE PRECISION,
    apartments_avg DOUBLE PRECISION,
    basementarea_avg DOUBLE PRECISION,
    commonarea_avg DOUBLE PRECISION,
    livingarea_avg DOUBLE PRECISION,
    obs_30_cnt_social_circle DOUBLE PRECISION,
    def_30_cnt_social_circle DOUBLE PRECISION,
    obs_60_cnt_social_circle DOUBLE PRECISION,
    def_60_cnt_social_circle DOUBLE PRECISION,
    legacy_amt_income_text VARCHAR(64) DEFAULT '',
    internal_sync_token VARCHAR(128) DEFAULT 'PENDING_MIGRATION'
);

CREATE TABLE IF NOT EXISTS src_bureau (
    sk_id_bureau BIGINT PRIMARY KEY,
    sk_id_curr BIGINT NOT NULL,
    credit_active VARCHAR(32),
    credit_currency VARCHAR(32),
    days_credit INTEGER,
    credit_day_overdue INTEGER,
    days_credit_enddate DOUBLE PRECISION,
    days_enddate_fact DOUBLE PRECISION,
    amt_credit_max_overdue DOUBLE PRECISION,
    cnt_credit_prolong INTEGER,
    amt_credit_sum DOUBLE PRECISION,
    amt_credit_sum_debt DOUBLE PRECISION,
    amt_credit_sum_limit DOUBLE PRECISION,
    amt_credit_sum_overdue DOUBLE PRECISION,
    credit_type VARCHAR(64),
    days_credit_update INTEGER,
    amt_annuity DOUBLE PRECISION,
    old_sys_bureau_ref VARCHAR(64) DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_src_bureau_sk_id_curr ON src_bureau(sk_id_curr);

CREATE TABLE IF NOT EXISTS src_bureau_balance (
    sk_id_bureau BIGINT NOT NULL,
    months_balance INTEGER NOT NULL,
    status VARCHAR(8),
    raw_status_dump TEXT DEFAULT '',
    PRIMARY KEY (sk_id_bureau, months_balance)
);
